title: Jekyll Dark Ored
email: sonlink.dourden@gmail.com
description: A simple dark orange red theme for Jekyll
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://son-link.github.io/jekyll-minimal-dark-orange/" # the base hostname & protocol for your site

# Social Network
social_links: true # If true show social links
rss: true
twitter: 'https://twitter.com/sonlink'
github: 'https://github.com/son-link'
gitlab: 'https://gitlab.com/son-link'
spotify: 'https://open.spotify.com/user/117752446'

plugins:
- jekyll-paginate
- jekyll-seo-tag

# Pagination
paginate: 3
paginate_path: "/page:num/"

include: ['_pages']

exclude:
  - vendor
  - screenshot.png
  - thumbnail.png
  - '*.gem*'
  - icons.js
  - config_fontello.json
  - assets/css/config.json

credits: |
  jekyll-minimal-dark-orange &copy; 2020 Alfonso Saavedra "Son Link"<br />
  Under the GNU/GPL 3 license. Powered by <a href="https://jekyllrb.com/" target="_black">Jekyll</a>.